---
- hosts: overcloud
  vars:
    metadata:
      name: Hardware Discovery
      description: Validations that run after the hardware was discovered.
      stage: discovery
- include: ../validations/discovery_diff.yaml
- include: ../validations/undercloud-disk-space.yaml
- include: ../validations/undercloud-ram.yaml
- include: ../validations/undercloud-cpu.yaml
- include: ../validations/512e.yaml
- include: ../validations/network_environment.yaml
- include: ../validations/check-network-gateway.yaml
- include: ../validations/instackenv.yaml
