---
- hosts: undercloud
  vars:
    metadata:
      name: Provide difference in hardware configuration
      description: This test provides difference in configuration based on data collected in ironic-inspector
      groups:
        - discovery
    swift_ironic_password: password
  tasks:
  - name: Run the Discovery diff
    discovery_diff:
      os_tenant_name: service
      os_username: ironic
      os_password: "{{ swift_ironic_password }}"
